# Use root/example as user/password credentials
version: '3.8'
services:

  mongo:
    image: mongo:noble
    restart: always
    ports: 
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: yazan
      MONGO_INITDB_ROOT_PASSWORD: yazan

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: yazan
      ME_CONFIG_MONGODB_ADMINPASSWORD: yazan
      ME_CONFIG_MONGODB_URL: mongodb://yazan:yazan@mongo:27017/
      ME_CONFIG_BASICAUTH: ""
    depends_on: [mongo]
